const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const sourceEntry = path.join(rootDir, 'src/index.js');
const distEntry = path.join(rootDir, 'dist/index.js');

fs.mkdirSync(path.dirname(distEntry), { recursive: true });

let code = fs.readFileSync(sourceEntry, 'utf8').trimEnd();

const digitalTwinExport = "// Re-export digital-twin bundle generated by Vite.\nexport * from './digital-twin.mjs';\n";

if (!code.includes("'./digital-twin.mjs'") && !code.includes('"./digital-twin.mjs"')) {
  code += digitalTwinExport;
}

fs.writeFileSync(distEntry, `${code}\n`, 'utf8');

console.log('build dist/index.js');
